import type { CheckoutStatusBillingAddress } from '@/interfaces/store.interfaces';
import type { InputField } from '@/interfaces/forms.interfaces';

export function createBillingFields(billingForm: CheckoutStatusBillingAddress): InputField[] {
  return [
    {
      id: 'first_name',
      label: 'Nombre',
      type: 'text',
      name: 'name',
      required: true,
      fullWidth: false,
      value: billingForm.first_name,
      placeholder: 'Nombre',
      ariaLabel: 'Nombre',
    },
    {
      id: 'last_name',
      label: 'Apellidos',
      type: 'text',
      name: 'last-name',
      required: true,
      fullWidth: false,
      value: billingForm.last_name,
      placeholder: 'Apellidos',
      ariaLabel: 'Apellidos',
    },
    {
      id: 'address_1',
      label: 'Dirección',
      type: 'text',
      name: 'street-address',
      required: true,
      fullWidth: true,
      value: billingForm.address_1,
      placeholder: 'Dirección',
      ariaLabel: 'Dirección',
    },
    {
      id: 'country',
      label: 'País',
      type: 'select',
      name: 'country',
      options: [{ value: 'ES', label: 'España', selected: true }],
      required: true,
      value: billingForm.country,
      placeholder: 'País',
      ariaLabel: 'País',
    },
    {
      id: 'city',
      label: 'Ciudad',
      type: 'text',
      name: 'city',
      required: true,
      value: billingForm.city,
      placeholder: 'Ciudad',
      ariaLabel: 'Ciudad',
    },
    {
      id: 'state',
      label: 'Provincia',
      type: 'text',
      name: 'state',
      required: true,
      value: billingForm.state,
      placeholder: 'Provincia',
      ariaLabel: 'Provincia',
    },
    {
      id: 'postcode',
      label: 'Código Postal',
      type: 'text',
      name: 'postcode',
      required: true,
      value: billingForm.postcode,
      placeholder: 'Código postal',
      ariaLabel: 'Código Postal',
    },
    {
      id: 'email',
      label: 'Correo Electrónico',
      type: 'email',
      name: 'email',
      required: true,
      value: billingForm.email,
      placeholder: 'Correo electrónico',
      ariaLabel: 'Correo Electrónico',
    },
    {
      id: 'phone',
      label: 'Teléfono',
      type: 'tel',
      name: 'phone',
      required: true,
      value: billingForm.phone,
      placeholder: 'Número de teléfono',
      ariaLabel: 'Teléfono',
    },
  ];
}
